---
# tasks file for roles/redis
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Wait for APT Lock
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install redis-server
  apt:
    name: 
    - redis-server
    - build-essential 
    - tcl 
    - make

- name: Enabled redis-server
  service:
    name: redis
    state: started
    enabled: yes

- name: Change redis2 conf
  copy:
    src: files/redis2.conf
    dest: /etc/redis/redis.conf
  when: ansible_ssh_host=="192.168.60.38"
  notify: restart redis

- name: Change redis2 conf
  copy:
    src: files/redis2.conf
    dest: /etc/redis/redis.conf
  when: ansible_ssh_host=="192.168.60.39"
  notify: restart redis

- name: Change redis3 conf
  copy:
    src: files/redis3.conf
    dest: /etc/redis/redis.conf
  when: ansible_ssh_host=="192.168.60.40"
  notify: restart redis

- name: wget http://download.redis.io/redis-stable.tar.gz
  shell: wget http://download.redis.io/redis-stable.tar.gz

- name: tar xzvf redis-stable.tar.gz
  shell: tar xzvf redis-stable.tar.gz

# - name: cd redis-stable
#   shell: cd redis-stable

# - name: cd /home/ubuntu/redis-stable/deps
#   shell: cd /home/ubuntu/redis-stable/deps

# - name: sudo make hiredis
#   make:
#     chdir: /home/ubuntu/redis-stable/deps/hiredis
#     target: install

# - name: sudo make jemalloc
#   make:
#     chdir: /home/ubuntu/redis-stable/deps/jemalloc
#     target: install

# - name: sudo make linenoise
#   make:
#     chdir: /home/ubuntu/redis-stable/deps/linenoise
#     target: install

# - name: sudo make lua
#   make:
#     chdir: /home/ubuntu/redis-stable/deps/lua
#     target: install

# - name: sudo make geohash-int
#   make:
#     chdir: /home/ubuntu/redis-stable/deps/geohash-int
#     target: install

# - name: sudo make
#   make:
#     chdir: /home/ubuntu/redis-stable

# - name: sudo make
#   make:
#     chdir: /home/ubuntu/redis-stable
#     target: test

# - name: cp /home/ubuntu/redis-stable/src/redis-cli /usr/local/bin/
#   shell: cp /home/ubuntu/redis-stable/src/redis-cli /usr/local/bin/

# - name: cp /home/ubuntu/redis-stable/src/redis-server /usr/local/bin/
#   shell: cp /home/ubuntu/redis-stable/src/redis-server /usr/local/bin/