---
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Wait for APT Lock
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install GItlab requirement
  apt:
    name: 
      - curl 
      - openssh-server
      - ca-certificates
      - postfix 
      - tzdata
    force_apt_get: yes
    state: latest

- name: Add GitLab repository
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash

- name: Install GitLab CE Community Edition
  shell: sudo apt-get install gitlab-ee