---
# tasks file for roles/java11
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Wait for APT Lock
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install Java
  apt:
    name: 
      - default-jre
      - default-jdk
    state: latest