---
# handlers file for roles/apache2
- name: start apache2
  service:
    name: apache2
    state: started

- name: stop apache2
  service:
    name: apache2
    state: stopped

- name: restart apache2
  service:
    name: apache2
    state: restarted