---
# handlers file for roles/mariadb
- name: start mariadb
  service:
    name: mariadb
    state: started

- name: stop mariadb
  service:
    name: mariadb
    state: stopped

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
