---
- name: Config master node
  copy:
    src: files/master_node.cnf
    dest: /etc/mysql/conf.d/galera.cnf
  when: ansible_ssh_host=="{{ node1 }}"  

- name: Config slave node1
  copy:
    src: files/slave_node1.cnf
    dest: /etc/mysql/conf.d/galera.cnf
  when: ansible_ssh_host=="{{ node2 }}"  

- name: Config slave node2
  copy:
    src: files/slave_node2.cnf
    dest: /etc/mysql/conf.d/galera.cnf
  when: ansible_ssh_host=="{{ node3 }}"  