---
- name: stop mysql
  service:
    name: mysql
    state: stopped

- name: create master galera node
  shell: sudo galera_new_cluster
  when: ansible_ssh_host=="192.168.60.38"  

- name: set cluster size
  shell: mysql -u root -p2508 -e "SHOW STATUS LIKE 'wsrep_cluster_size'"
  when: ansible_ssh_host=="192.168.60.38"

- name: create slave galera node1
  shell: sudo systemctl start mysql
  when: ansible_ssh_host=="192.168.60.39"  

- name: create slave galera node1
  shell: mysql -u root -p2508 -e "SHOW STATUS LIKE 'wsrep_cluster_size'"
  when: ansible_ssh_host=="192.168.60.39"  

- name: create slave galera node2
  shell: sudo systemctl start mysql
  when: ansible_ssh_host=="192.168.60.40"  


- name: create slave galera node2
  shell:  mysql -u root -p2508 -e "SHOW STATUS LIKE 'wsrep_cluster_size'"
  when: ansible_ssh_host=="192.168.60.40"  


- name: CREATE DATABASE playground
  shell: mysql -u root -p2508 -e 'CREATE DATABASE playground';
  when: ansible_ssh_host=="192.168.60.38"  

- name: CREATE DATABASE playground.equipment
  shell: mysql -u root -p2508 -e 'CREATE TABLE playground.equipment ( id INT NOT NULL AUTO_INCREMENT, type VARCHAR(50), quant INT, color VARCHAR(25), PRIMARY KEY(id));'
  when: ansible_ssh_host=="192.168.60.38"  

- name: Insert data playground.equipment
  shell: mysql -u root -p2508 -e 'INSERT INTO playground.equipment (type, quant, color) VALUES ("slide", 2, "blue");'
  when: ansible_ssh_host=="192.168.60.38"  

- name: Insert data playground.equipment (2)
  shell: mysql -u root -p2508 -e 'INSERT INTO playground.equipment (type, quant, color) VALUES ("swing", 10, "yellow");'
  when: ansible_ssh_host=="192.168.60.39" 

- name: Insert data playground.equipment (3)
  shell: mysql -u root -p2508 -e 'INSERT INTO playground.equipment (type, quant, color) VALUES ("seesaw", 3, "green");'
  when: ansible_ssh_host=="192.168.60.40" 
