---
- name: All access mysql 
  copy:
    src: files/50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf

- name: Sets the root password  (1)
  shell: mysql -u {{ mysql_user }} -p{{ mysql_password }} -e  "SET old_passwords=0;"

- name: Sets the root password  (2)
  shell: mysql -u {{ mysql_user }} -p{{ mysql_password }} -e  "GRANT SELECT ON *.* TO {{ mysql_user }}@localhost IDENTIFIED BY '{{ mysql_password }}';"

- name: Sets the remote user password  (1)
  shell: mysql -u {{ mysql_user }} -p{{mysql_password }} -e  "CREATE OR REPLACE USER {{ mysql_remote_user }}@localhost IDENTIFIED BY '{{mysql_remote_password }}';"

- name: Sets the remote user password  (2)
  shell: mysql -u {{ mysql_user }} -p{{mysql_password }} -e  "GRANT ALL PRIVILEGES ON *.* TO '{{ mysql_remote_user }}'@'%' IDENTIFIED BY '{{ mysql_remote_password }}';"

- name: Sets the root password FLUSH PRIVILEGES
  shell: mysql -u {{ mysql_user }} -p{{ mysql_password }} -e "FLUSH PRIVILEGES;"

- name: restart mariadb
  service:
    name: mariadb
    state: restarted