- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install haproxy
  shell: sudo apt-get install haproxy -y

- name: Enabled Haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Install linux-headers-$(uname -r)
  shell: sudo apt-get install linux-headers-$(uname -r) -y

- name: Install keepalived
  shell: sudo apt-get install keepalived -y

- name: Enabled keepalived
  service:
    name: keepalived
    state: started
    enabled: yes

- name: Config Keepalive (1)
  shell: sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf

- name: Config Keepalive (2)
  shell: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf

- name: Config Keepalive (3)
  shell: sysctl -p

- name: Change haproxy Gluster1
  copy:
    src: files/keepalived_node1.conf
    dest: /etc/keepalived/keepalived.conf
  when: ansible_ssh_host==gluster_node1
  notify:
    - restart keepalived
    - restart haproxy

- name: Change haproxy Gluster2
  copy:
    src: files/keepalived_node2.conf
    dest: /etc/keepalived/keepalived.conf
  when: ansible_ssh_host==gluster_node2
  notify: 
    - restart keepalived
    - restart haproxy