---
# tasks file for roles/ansible
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Wait for APT Lock
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install software-properties-common
  apt:
    name: software-properties-common

- name: sudo apt-add-repository --yes --update ppa:ansible/ansible
  shell: sudo apt-add-repository --yes --update ppa:ansible/ansible

- name: Install ansible
  apt:
    name: ansible

- name: Add id_rsa file
  copy:
    src: files/id_rsa
    dest: ~/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'