---
# tasks file for roles/ansible
- name: Download jenkins repo
  shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add - 

- name: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ >> /etc/apt/sources.list'
  shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ >> /etc/apt/sources.list'

- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install software-properties-common
  apt:
    name: software-properties-common

- name: sudo apt-add-repository --yes --update ppa:ansible/ansible
  shell: sudo apt-add-repository --yes --update ppa:ansible/ansible

- name: Add id_rsa file
  copy:
    src: files/id_rsa
    dest: ~/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'