---
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
    
- name: Update apt
  apt:
    update_cache: yes

- name: Install requirement software
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl 
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker’s official GPG key
  shell:  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Docker’s official GPG key (2)
  shell:  sudo apt-key fingerprint 0EBFCD88

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: Install docker engine
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Config user docker
  shell: sudo usermod -aG docker ubuntu