---
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Wait for APT Lock
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: Install PHP 
  apt: 
    name: 
      - php{{ php_version }} 
      - libapache2-mod-php{{ php_version }}
      - php{{ php_version }}-mysql 
      - php-common
      - php{{ php_version }}-cli 
      - php{{ php_version }}-common
      - php{{ php_version }}-json 
      - php{{ php_version }}-opcache
      - php{{ php_version }}-readline
  when: php_version == 7.2

- name : Enable the Apache php7.2
  shell: sudo a2enmod php{{ php_version }}
  when: php_version == 7.2

- name: Copy phpinfo to server
  copy:
    src: files/info.php
    dest: /var/www/html/
  when: php_version == 7.2

- name : Enable the Apache php7.2
  shell: sudo a2dismod  php{{ php_version }}
  when: php_version == 7.2

- name: Install PHP FPM
  apt: 
    name: 
      - php{{ php_version }}-fpm
  when: php_version == 7.2

- name: nable proxy_fcgi and setenvif module. 
  shell: sudo a2enmod proxy_fcgi setenvif 
  when: php_version == 7.2

- name: Enable the /etc/apache2/conf-available/php{{ php_version }}-fpm.conf configuration file.
  shell: sudo a2enconf php{{ php_version }}-fpm
  notify: restart apache2
  when: 
  - php_version == 7.2 
  - lamp == "yes"